// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('react');
var { Component } = React;
var ReactNative = require('react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function (appParameters) {
  AppRegistry.runApplication('rn', appParameters);
});
require('../index.js');
